### ISSUE TITLE
Phat (Substrate) Contract Testing Command Fails with Devphase

### ISSUE THREAD

**Issue by FaisalAl-Tameemi** [Phala-Network/phat-offchain-rollup#27]
Running `yarn devphase contract test` within the `./phat` repo fails with the following log:

![Screenshot from 2023-06-11 20-42-15](https://github.com/Phala-Network/phat-offchain-rollup/assets/4079648/3a482f13-e340-4b32-8900-c555c9fc0f5e)

Specs:
* Pop OS (Ubuntu): `22.04 LTS`
* Node: `16.20`
* Yarn: `1.22.19`
* Devphase (in `./phat/package.json`): `^0.2.2`
* Stack Version (`./phat/devphase.config.ts`): `latest`
* Rust Toolchain: `nightly-2023-02-03`
* Cargo version: `1.69.0-nightly`

Added context:
* I'm only interested in the substrate tests and thus removed the `evm_price_feed` contract from the Cargo workspace locally to avoid it building. This was also done for the associated test.
* Contract building and functionality is all working (using `yarn devphase contract compile`). Tested by deploying the compiled contracts using PoC5 testnet.

---

_Originally posted by @FaisalAl-Tameemi in https://github.com/Phala-Network/phat-offchain-rollup/issues/26#issuecomment-1586240789_

**Comment by l00k** [comment]
You can specify "-v" param to get more verbose output.

But direct issue was with outdated devphase ;) for the first glance all is ok (version number), but now `@devphase/cli` should be used instead of `devphase`.

1. delete `devphase.config.ts` (it is outdated)
2. switch `devphase: 0.2.2` to `@devphase/cli: ^0.2.1` in `package.json`

**Comment by FaisalAl-Tameemi** [comment]
Awesome, that did it :+1:

**Comment by h4x3rotab** [comment]
Glad to see the problem was solved. Thank you, @l00k, for the help!

I have a few questions for @l00k:

1. Why do you suggest to delete `devphase.config.ts`? Do you mean the content is outdated, or the config file is deprecated?
2. Do you suggest to install devphase globally or use `npx` to execute it? I used to run `npx devphase <command...>` in the past.

**Comment by l00k** [comment]
@h4x3rotab those short term solution suggestions.

>     1. Why do you suggest to delete `devphase.config.ts`? Do you mean the content is outdated, or the config file is deprecated?
In this case config file was outdated. Most of fields were just in default state so I don't think it is reasonable to leave them here. I think we should leave only fields where really "configure" something. The rest should be removed and only mentioned (described on `devphase` site)

>     2. Do you suggest to install devphase globally or use `npx` to execute it? I used to run `npx devphase <command...>` in the past.
`@devphase/cli` could be used as global package. As long as user use both devphase and Phala binaries from latest release there is no need to include this package in dependencies. In some cases devphase and Phala binaries may not work properly (old release) but those are edge cases.
I personally prefer to include such things in project `package.json` but that is only my preference.
